# -*- coding: utf-8 -*-
from pathlib import Path
import json

out = Path(__file__).resolve().parent
records = []


def add(**kw):
    records.append(kw)


hk_common_eng = (
    "一般：TOEFL iBT≥80 或 IELTS 6.5（分项≥5.5）；院系可能更高。"
    "英语授课学位可豁免（以官网为准）。"
)
hk_req = (
    "学士（优秀）或硕士；研究计划/套磁导师强烈建议；"
    "成绩单、推荐信2封、CV、学位证明。"
)

# ========== HONG KONG LOCAL ==========
add(
    id="hkpfs",
    region="hk",
    regionLabel="香港本地",
    degree="phd",
    school="Hong Kong PhD Fellowship Scheme (HKPFS)",
    campus="香港8校通用",
    qsCs2026="奖学金",
    fields=["All STEM"],
    program="RGC 香港博士研究生奖学金计划 2027/28",
    intake="2027/28",
    deadline="2026-12-01",
    deadlineDetail=(
        "Step1 RGC 初始申请截止 12:00 noon HKT；"
        "Step2 各大学全日申请 23:59。最多选2个项目/学校。"
    ),
    english="满足目标大学要求",
    requirements="一次性 RGC 申请；再向大学提交完整材料并填写 HKPFS 编号。",
    funding="月约 HK$28,700 + 年差旅 HK$14,400；约400个名额。",
    fundingLevel="full",
    applyUrl="https://cerg1.ugc.edu.hk/hkpfs/apply.html",
    portalName="HKPFSES (RGC)",
    notes="未中 HKPFS 仍可能获大学 PGS 录取。",
    confidence="high",
    source="RGC / PolyU HKPFS Guide / 2027报道",
)

add(
    id="hku-cds-phd",
    region="hk",
    regionLabel="香港本地",
    degree="phd",
    school="The University of Hong Kong (HKU)",
    campus="香港·薄扶林",
    qsCs2026="=27",
    fields=["CS", "Data Science", "AI"],
    program="School of Computing & Data Science — MPhil/PhD",
    intake="2027/28 Fall（亦可有 Spring 清理轮）",
    deadline="2026-12-01",
    deadlineDetail=(
        "主轮：约2026-09-01开放；HKPFS与校内截止均为2026-12-01"
        "（RGC中午；学校23:59）。可能另有4月/8月清理轮。"
    ),
    english="CS：TOEFL iBT≥85；可用IELTS等；非英语授课背景须提交语言成绩。",
    requirements=hk_req + " 需 Research Proposal。",
    funding="有 — 常规PGS；HKPFS：月约HK$28,700+年差旅HK$14,400。",
    fundingLevel="full",
    applyUrl="https://gradsch.hku.hk/",
    portalName="HKU Online Application + RGC HKPFSES",
    notes="须先拿HKPFS Reference Number再填港大系统。",
    confidence="high",
    source="HKU Grad School / CS / HKPFS",
)

add(
    id="hku-ee-phd",
    region="hk",
    regionLabel="香港本地",
    degree="phd",
    school="The University of Hong Kong (HKU)",
    campus="香港",
    qsCs2026="=27",
    fields=["EE", "ECE"],
    program="Electrical & Electronic Engineering — MPhil/PhD",
    intake="2027/28 Fall",
    deadline="2026-12-01",
    deadlineDetail="与研究生院主轮/HKPFS同步（确认院系页）。",
    english=hk_common_eng,
    requirements=hk_req,
    funding="有 — PGS / HKPFS",
    fundingLevel="full",
    applyUrl="https://www.eee.hku.hk/",
    portalName="HKU Online Application",
    notes="EE与Computing分属不同学院。",
    confidence="medium",
    source="HKU EEE",
)

add(
    id="cuhk-eng-phd",
    region="hk",
    regionLabel="香港本地",
    degree="phd",
    school="The Chinese University of Hong Kong (CUHK)",
    campus="香港·沙田",
    qsCs2026="37",
    fields=["CS", "EE", "IE", "AI"],
    program="Faculty of Engineering — MPhil-PhD / PhD",
    intake="2027/28",
    deadline="2026-12-01",
    deadlineDetail="HKPFS：RGC 12:00；CUHK全日申请同日23:59。",
    english="TOEFL iBT≥79 或 IELTS 6.5（院系可更高）。",
    requirements="学士；推荐信；研究兴趣说明；建议联系导师。",
    funding=(
        "有 — PGS约HK$229,200/年(2026-27)；HKPFS；"
        "未获HKPFS提名人可获VC PhD Scholarship HK$80,000。"
    ),
    fundingLevel="full",
    applyUrl="https://www.gs.cuhk.edu.hk/",
    portalName="CUHK GS Online Application + RGC",
    notes="香港CUHK与深圳CUHK-Shenzhen是不同申请系统。",
    confidence="high",
    source="CUHK GS booklet / HKPFS",
)

add(
    id="hkust-cse-phd",
    region="hk",
    regionLabel="香港本地",
    degree="phd",
    school="HKUST (Clear Water Bay)",
    campus="香港·清水湾",
    qsCs2026="33",
    fields=["CS", "ECE", "AI", "Data"],
    program="CSE / ECE — MPhil & PhD",
    intake="2027/28 Fall；部分Spring",
    deadline="2026-12-01",
    deadlineDetail=(
        "申请自2026-09-01开放；HKPFS截止2026-12-01；"
        "其后滚动至2027-08（各项目不同，尽早投）。"
    ),
    english="TOEFL iBT≥80或IELTS 6.5（分项≥5.5）；英语授课本科可豁免。",
    requirements=hk_req,
    funding="有 — PGS约HK$229,620/年（PhD最长4年）；HKPFS。学费RPg约HK$49,500/年。",
    fundingLevel="full",
    applyUrl="https://fytgs.hkust.edu.hk/apply",
    portalName="HKUST FYTGS + RGC",
    notes="与广州校区HKUST(GZ)独立招生。",
    confidence="high",
    source="HKUST PG Flyer 2027-28",
)

add(
    id="cityu-cs-phd",
    region="hk",
    regionLabel="香港本地",
    degree="phd",
    school="City University of Hong Kong (CityUHK)",
    campus="香港·九龙塘",
    qsCs2026="=67",
    fields=["CS", "EE", "Data"],
    program="Computer Science / EE — PhD",
    intake="2027/28",
    deadline="2026-12-01",
    deadlineDetail="HKPFS与校内全日申请通常同日截止。",
    english=hk_common_eng,
    requirements=hk_req,
    funding="有 — PGS + HKPFS",
    fundingLevel="full",
    applyUrl="https://www.cityu.edu.hk/pg/",
    portalName="CityU SGS + RGC",
    notes="",
    confidence="high",
    source="HKPFS university list",
)

add(
    id="polyu-comp-phd",
    region="hk",
    regionLabel="香港本地",
    degree="phd",
    school="The Hong Kong Polytechnic University (PolyU)",
    campus="香港·红磡",
    qsCs2026="70",
    fields=["CS", "EE", "Computing"],
    program="Computing / EE — PhD",
    intake="2027/28 Semester 1 (Sept 2027)",
    deadline="2026-12-01",
    deadlineDetail="RGC初始申请12:00；PolyU RPgAdmission 23:59；选2027/28 Semester 1。",
    english="须有效英语成绩或英语授课证明。",
    requirements=hk_req + " 可向两个不同院系各交一份完整申请。",
    funding="有 — PGS + HKPFS强化包（见PolyU指南）",
    fundingLevel="full",
    applyUrl="https://www.polyu.edu.hk/gs/",
    portalName="PolyU RPgAdmission + RGC",
    notes="从2026-09-01起可递交HKPFS。",
    confidence="high",
    source="PolyU HKPFS Guide PDF",
)

add(
    id="hkbu-sci-phd",
    region="hk",
    regionLabel="香港本地",
    degree="phd",
    school="Hong Kong Baptist University (HKBU)",
    campus="香港",
    qsCs2026="—",
    fields=["CS", "Science"],
    program="Computer Science — PhD/MPhil",
    intake="2027/28",
    deadline="2026-12-01",
    deadlineDetail="HKPFS参与院校，截止同主轮。",
    english=hk_common_eng,
    requirements=hk_req,
    funding="有 — PGS / HKPFS",
    fundingLevel="full",
    applyUrl="https://gs.hkbu.edu.hk/",
    portalName="HKBU GS + RGC",
    notes="与珠海BNBU有合作路径，但是不同校园。",
    confidence="medium",
    source="HKPFS",
)

add(
    id="ln-sci-phd",
    region="hk",
    regionLabel="香港本地",
    degree="phd",
    school="Lingnan University",
    campus="香港·屯门",
    qsCs2026="—",
    fields=["Data Science"],
    program="Selected STEM / DS research PhD",
    intake="2027/28",
    deadline="2026-12-01",
    deadlineDetail="HKPFS截止日。",
    english=hk_common_eng,
    requirements=hk_req,
    funding="有 — HKPFS / 校内奖学金（规模小于理工校）",
    fundingLevel="partial",
    applyUrl="https://www.ln.edu.hk/sgs/",
    portalName="Lingnan SGS + RGC",
    notes="CS体量较小。",
    confidence="medium",
    source="HKPFS",
)

add(
    id="eduhk-phd",
    region="hk",
    regionLabel="香港本地",
    degree="phd",
    school="The Education University of Hong Kong (EdUHK)",
    campus="香港",
    qsCs2026="—",
    fields=["EdTech", "AI in Education"],
    program="PhD (AI/教育科技相关)",
    intake="2027/28",
    deadline="2026-12-01",
    deadlineDetail="HKPFS参与。",
    english=hk_common_eng,
    requirements=hk_req,
    funding="有 — HKPFS/PGS",
    fundingLevel="partial",
    applyUrl="https://www.eduhk.hk/gradsch/",
    portalName="EdUHK + RGC",
    notes="偏教育交叉。",
    confidence="medium",
    source="HKPFS",
)

for mid, school, camp, url, note in [
    (
        "hku-msc",
        "The University of Hong Kong (HKU)",
        "香港",
        "https://admissions.hku.hk/tpg",
        "研究型请看MPhil/PhD。",
    ),
    (
        "cuhk-msc",
        "The Chinese University of Hong Kong (CUHK)",
        "香港·沙田",
        "https://www.gs.cuhk.edu.hk/",
        "",
    ),
    (
        "hkust-msc",
        "HKUST (Clear Water Bay)",
        "香港·清水湾",
        "https://fytgs.hkust.edu.hk/programs",
        "MPhil属研究型，资助更好。",
    ),
    (
        "cityu-msc",
        "City University of Hong Kong",
        "香港",
        "https://www.cityu.edu.hk/pg/",
        "",
    ),
    (
        "polyu-msc",
        "Hong Kong Polytechnic University",
        "香港",
        "https://www.polyu.edu.hk/study/",
        "",
    ),
]:
    add(
        id=mid,
        region="hk",
        regionLabel="香港本地",
        degree="master",
        school=school,
        campus=camp,
        qsCs2026="见同校PhD",
        fields=["CS", "EE", "AI"],
        program="授课型硕士（MSc等，非研究型）",
        intake="2027 Fall为主",
        deadline="滚动/多轮（常为2026末–2027春）",
        deadlineDetail="授课型硕士通常不走HKPFS；请查各MSc项目页。",
        english="IELTS/TOEFL因项目而异（常见6.0–6.5）。",
        requirements="学士学位、成绩单、推荐信、个人陈述；一般无需套磁。",
        funding="多数自费；少量入学奖学金，远少于PhD PGS。",
        fundingLevel="rare",
        applyUrl=url,
        portalName="各校授课型硕士申请系统",
        notes=note + " 本表将硕士与PhD严格分开。",
        confidence="medium",
        source="各校TPg惯例",
    )

# ========== HK MAINLAND ==========
add(
    id="hkustgz-phd",
    region="hk_mainland",
    regionLabel="香港院校·大陆校区",
    degree="phd",
    school="HKUST (Guangzhou)",
    campus="广州·南沙",
    qsCs2026="（港科大体系）",
    fields=["AI", "IoT", "Computational Media"],
    program="PhD（各Hub/Thrust，如Artificial Intelligence）",
    intake="2027 Spring（01-25）或 2027 Fall（09-01）",
    deadline="2026-12-04",
    deadlineDetail=(
        "Spring2027：国际生至2026-12-04；内地生至2026-12-25。"
        "Fall2027：国际生可至2027-06-15（滚动，越早越好）。"
    ),
    english="英语授课；IELTS/TOEFL按研究生院要求。",
    requirements="学士/硕士；套磁导师；成绩单、推荐信、研究陈述。",
    funding="有 — PGS（公开材料常见约CNY15,000/月量级，以录取通知为准）。",
    fundingLevel="full",
    applyUrl="https://fytgs.hkust-gz.edu.cn/",
    portalName="HKUST(GZ) FYTGS Application",
    notes="与清水湾校区分开申请。",
    confidence="high",
    source="HKUST(GZ) Admission Timeline",
)

add(
    id="cuhksz-cie-phd",
    region="hk_mainland",
    regionLabel="香港院校·大陆校区",
    degree="phd",
    school="CUHK-Shenzhen",
    campus="深圳",
    qsCs2026="（港中深）",
    fields=["CS", "IE", "AI", "EE"],
    program="PhD in Computer and Information Engineering等",
    intake="2027 Fall",
    deadline="2027-03-09",
    deadlineDetail="第三方汇总显示CIE PhD约2027-03-09；务必以港中深官网为准。",
    english="IELTS约5.5–6.0起（项目页）；建议冲更高。",
    requirements="学士/硕士；研究潜力；推荐信。",
    funding="有 — 奖学金/助研常见（覆盖学费+生活津贴，以录取为准）。",
    fundingLevel="full",
    applyUrl="https://www.cuhk.edu.cn/en",
    portalName="CUHK-Shenzhen Graduate Admissions",
    notes="不是沙田CUHK通道。",
    confidence="medium",
    source="GlobalAdmissions CIE listing",
)

add(
    id="bnbu-cs-phd",
    region="hk_mainland",
    regionLabel="香港院校·大陆校区",
    degree="phd",
    school="BNBU / UIC (北师港浸大)",
    campus="珠海",
    qsCs2026="—",
    fields=["CS", "Applied Math", "Stats"],
    program="PhD / MPhil（Computer Science and Technology等）",
    intake="滚动",
    deadline="滚动（全年）",
    deadlineDetail="CS/数学等若干方向全年受理；尽早+先获导师确认。",
    english="TOEFL或IELTS（官网细则）。",
    requirements="须与拟任导师沟通并获确认；RP、成绩单、推荐人等。",
    funding="有限/项目制 — 查研究生院；可有HKBU联合培养。",
    fundingLevel="partial",
    applyUrl="https://gs.bnbu.edu.cn/",
    portalName="BNBU Graduate School",
    notes="原UIC；港浸会合作办学。",
    confidence="high",
    source="BNBU GS / FAQ",
)

add(
    id="hkustgz-mphil",
    region="hk_mainland",
    regionLabel="香港院校·大陆校区",
    degree="master",
    school="HKUST (Guangzhou)",
    campus="广州·南沙",
    qsCs2026="—",
    fields=["AI", "Tech"],
    program="Red Bird MPhil / 研究型硕士相关",
    intake="2027 Fall",
    deadline="见学院页",
    deadlineDetail="Red Bird MPhil请看College of Future Technology专项时间。",
    english="英语",
    requirements="学士",
    funding="研究型可能有津贴；授课型多为自费。",
    fundingLevel="partial",
    applyUrl="https://fytgs.hkust-gz.edu.cn/",
    portalName="HKUST(GZ)",
    notes="与PhD通道不同。",
    confidence="medium",
    source="HKUST(GZ) timeline",
)

# ========== SINGAPORE ==========
add(
    id="nus-cs-phd",
    region="singapore",
    regionLabel="新加坡",
    degree="phd",
    school="National University of Singapore (NUS)",
    campus="新加坡",
    qsCs2026="=4",
    fields=["CS", "AI"],
    program="PhD in Computer Science (NUS Computing)",
    intake="Aug 2027 / Jan 2028",
    deadline="2026-12-15",
    deadlineDetail="August入学截止12月15日；January入学截止6月15日。",
    english="非英语授课背景通常需TOEFL/IELTS。",
    requirements="CS/相关优秀本科；推荐信、成绩单；申请费S$50。",
    funding="有 — Research Scholarship（学费全免+月津贴；QE后top-up）。亦可SINGA/AISG。",
    fundingLevel="full",
    applyUrl="https://www.comp.nus.edu.sg/programmes/pg/phdcs/application/",
    portalName="NUS Graduate Admission (GDA)",
    notes="QS CS 2026并列第4。",
    confidence="high",
    source="NUS Computing",
)

add(
    id="ntu-ccds-phd",
    region="singapore",
    regionLabel="新加坡",
    degree="phd",
    school="Nanyang Technological University (NTU)",
    campus="新加坡",
    qsCs2026="9",
    fields=["CS", "Data Science", "AI"],
    program="PhD — College of Computing and Data Science",
    intake="Aug 2027 / Jan",
    deadline="2027-01-31",
    deadlineDetail="大学研究型：Aug轮门户约10月开，截止1月31日；部分学院更早。",
    english="TOEFL/IELTS；GRE可能要求。",
    requirements="优秀学士；研究计划；推荐信（至少一学术推荐）。",
    funding="有 — NTU Research Scholarship / SINGA / AISG等。",
    fundingLevel="full",
    applyUrl="https://www.ntu.edu.sg/admissions/graduate/radmissionguide",
    portalName="NTU Graduate Research Admission",
    notes="",
    confidence="high",
    source="NTU admission guide",
)

add(
    id="smu-scis-phd",
    region="singapore",
    regionLabel="新加坡",
    degree="phd",
    school="Singapore Management University (SMU)",
    campus="新加坡",
    qsCs2026="—",
    fields=["CS", "IS", "AI"],
    program="PhD — School of Computing and Information Systems",
    intake="Aug 2027 (Term 1)",
    deadline="2027-01-31",
    deadlineDetail="Term1 Aug2027：2026-08-01至2027-01-31。",
    english="非英语授课需TOEFL/IELTS；GRE/GMAT（本地四校本硕可豁免GRE）。",
    requirements="全职；完整材料+申请费。",
    funding="有 — 全额奖学金 / Presidential Doctoral Fellowship等。",
    fundingLevel="full",
    applyUrl="https://computing.smu.edu.sg/phd/online-application",
    portalName="SMU SCIS PhD Online Application",
    notes="",
    confidence="high",
    source="SMU SCIS",
)

add(
    id="sutd-phd",
    region="singapore",
    regionLabel="新加坡",
    degree="phd",
    school="SUTD",
    campus="新加坡",
    qsCs2026="—",
    fields=["CS", "ESD", "EPD", "AI"],
    program="PhD (ISTD等)",
    intake="Aug/Jan",
    deadline="查官网（常与SINGA协同）",
    deadlineDetail="可走校内申请或SINGA。",
    english="英语授课为主",
    requirements="优秀理工背景",
    funding="有 — SUTD Fellowship / SINGA",
    fundingLevel="full",
    applyUrl="https://www.sutd.edu.sg/",
    portalName="SUTD Graduate Admission",
    notes="",
    confidence="medium",
    source="SUTD/SINGA",
)

add(
    id="singa",
    region="singapore",
    regionLabel="新加坡",
    degree="phd",
    school="SINGA (A*STAR + NUS/NTU/SUTD/SMU/SIT)",
    campus="新加坡",
    qsCs2026="奖学金通道",
    fields=["CS", "AI", "Eng", "Science"],
    program="Singapore International Graduate Award — PhD",
    intake="Aug 2027",
    deadline="2026-12-01",
    deadlineDetail="Aug2027：2026-12-01 23:59 SGT；Jan2028：2027-06-01（仅部分机构）。",
    english="英语；按SINGA/院校要求。",
    requirements="国际生；科学工程方向；在线申请。",
    funding="全奖 — 学费全免；月津贴约S$2,700起（QE后升高）；机票与安家费。",
    fundingLevel="full",
    applyUrl="https://www.a-star.edu.sg/Scholarships/for-graduate-studies/singapore-international-graduate-award-singa",
    portalName="A*STAR SINGA Applicant Portal",
    notes="可与各校普通申请并行了解。",
    confidence="high",
    source="SINGA 2027 listings",
)

add(
    id="aisg",
    region="singapore",
    regionLabel="新加坡",
    degree="phd",
    school="AI Singapore PhD Fellowship",
    campus="新加坡AU",
    qsCs2026="奖学金",
    fields=["AI"],
    program="AISG PhD Fellowship（NUS/NTU/SMU/SUTD）",
    intake="通常Aug",
    deadline="提名制（跟院校录取）",
    deadlineDetail="先申请院校AI相关PhD，由大学提名AISG。",
    english="按院校",
    requirements="已申请/录取新加坡AU的AI PhD",
    funding="高额 — 月津贴可达约S$6,300–6,700（国籍档不同）+学费等。",
    fundingLevel="full",
    applyUrl="https://aisingapore.org/research/phd-fellowship-programme/",
    portalName="经院校提名 → AISG",
    notes="非直接个人门户为主。",
    confidence="medium",
    source="AISG",
)

add(
    id="nus-msc",
    region="singapore",
    regionLabel="新加坡",
    degree="master",
    school="NUS",
    campus="新加坡",
    qsCs2026="=4",
    fields=["CS"],
    program="MComp / 授课型硕士等",
    intake="Aug",
    deadline="多轮（常早于PhD）",
    deadlineDetail="授课型与研究型分开。",
    english="TOEFL/IELTS",
    requirements="学士",
    funding="多数自费",
    fundingLevel="rare",
    applyUrl="https://www.comp.nus.edu.sg/",
    portalName="NUS",
    notes="",
    confidence="medium",
    source="NUS",
)

# ========== JAPAN ==========
for item in [
    dict(
        id="utokyo-ist",
        school="The University of Tokyo",
        qs="41",
        fields=["CS", "EE", "IST"],
        program="IST / Engineering PhD",
        deadline="院系不同（常见2026-11~2027-01）",
        detail="须先取得教授内诺再网申；4月/10月入学。",
        url="https://www.i.u-tokyo.ac.jp/index_e.shtml",
        fund="有 — MEXT / UTokyo Fellowship / 实验室经费",
        conf="medium",
    ),
    dict(
        id="science-tokyo",
        school="Institute of Science Tokyo",
        qs="18",
        fields=["CS", "EE"],
        program="PhD (原Tokyo Tech体系)",
        deadline="查各学院（秋/春）",
        detail="原东工大CS/EE强；国际项目英语可选。",
        url="https://www.isct.ac.jp/",
        fund="有 — MEXT / 大学奖学金 / RA",
        conf="medium",
    ),
    dict(
        id="kyoto-phd",
        school="Kyoto University",
        qs="~95",
        fields=["CS", "EE"],
        program="Informatics / Engineering PhD",
        deadline="滚动+教授内诺",
        detail="先联系导师；MEXT大学推荐窗口常在秋冬。",
        url="https://www.kyoto-u.ac.jp/",
        fund="有 — MEXT / 内部fellowship",
        conf="medium",
    ),
    dict(
        id="tohoku-phd",
        school="Tohoku University",
        qs="—",
        fields=["CS", "EE"],
        program="PhD",
        deadline="教授路径2026-10~2027-01",
        detail="工程强校；英语项目存在。",
        url="https://www.tohoku.ac.jp/",
        fund="有 — MEXT等",
        conf="medium",
    ),
    dict(
        id="osaka-phd",
        school="Osaka University",
        qs="—",
        fields=["CS", "EE"],
        program="IST / Engineering PhD",
        deadline="查大学院",
        detail="需导师同意。",
        url="https://www.osaka-u.ac.jp/",
        fund="有 — MEXT / 大学",
        conf="low",
    ),
    dict(
        id="oist-phd",
        school="OIST",
        qs="—",
        fields=["CS", "AI", "Interdisciplinary"],
        program="PhD (5-year integrated)",
        deadline="约2026-11（2027-04入学）",
        detail="全英文；旋转实验室；自动资助。",
        url="https://www.oist.jp/admissions",
        fund="全奖 — 自动提供（学费+津贴）",
        conf="high",
    ),
]:
    add(
        id=item["id"],
        region="japan",
        regionLabel="日本",
        degree="phd",
        school=item["school"],
        campus="日本",
        qsCs2026=item["qs"],
        fields=item["fields"],
        program=item["program"],
        intake="2027 Apr / Oct",
        deadline=item["deadline"],
        deadlineDetail=item["detail"],
        english="多数理工国际项目英语可完成；MEXT有时不强制雅思。",
        requirements="强烈依赖导师内诺；成绩单、研究计划、推荐信。",
        funding=item["fund"],
        fundingLevel="full",
        applyUrl=item["url"],
        portalName="各大学院 + 导师邮件",
        notes="日本申请以「套磁→内诺→正式网申/MEXT」为主。",
        confidence=item["conf"],
        source="大学页/汇总",
    )

add(
    id="jp-master",
    region="japan",
    regionLabel="日本",
    degree="master",
    school="UTokyo / Science Tokyo / Kyoto等",
    campus="日本",
    qsCs2026="—",
    fields=["CS", "EE"],
    program="Master's（往往与博士连贯）",
    intake="2027 Apr/Oct",
    deadline="与博士类似，先导师",
    deadlineDetail="研究型修士同样需内诺。",
    english="英语或日语项目分流",
    requirements="学士+导师",
    funding="MEXT竞争；自费常见",
    fundingLevel="partial",
    applyUrl="https://www.studyinjapan.go.jp/",
    portalName="Study in Japan / 各校",
    notes="",
    confidence="medium",
    source="惯例",
)

# ========== KOREA ==========
add(
    id="kaist-phd",
    region="korea",
    regionLabel="韩国",
    degree="phd",
    school="KAIST",
    campus="大田",
    qsCs2026="前列（工程）",
    fields=["CS", "EE", "AI"],
    program="International Graduate — MS/PhD",
    intake="Spring 2027；Fall 2027",
    deadline="2026-09-01",
    deadlineDetail=(
        "Spring2027：网申2026-08-18～09-01；推荐信至09-08；结果约12-18。"
        "Fall2027：官网TBA（惯例Early≈12月，Regular≈3月）。"
    ),
    english="英语授课项目为主。",
    requirements="国际生通道；材料+推荐信。",
    funding="有 — 全额学费减免+月津贴+医保（以录取为准）。",
    fundingLevel="full",
    applyUrl="https://admission.kaist.ac.kr/intl-graduate/",
    portalName="KAIST International Graduate Admission",
    notes="CS/EE均可在国际研究生通道申请。",
    confidence="high",
    source="KAIST Yearly Timelines",
)

add(
    id="snu-phd",
    region="korea",
    regionLabel="韩国",
    degree="phd",
    school="Seoul National University (SNU)",
    campus="首尔",
    qsCs2026="47",
    fields=["CS", "EE"],
    program="Graduate (International)",
    intake="Spring 2027",
    deadline="2026-07-09",
    deadlineDetail=(
        "Spring2027国际生网申：2026-07-06 10:00 – 07-09 17:00 KST（窗口极短）；"
        "推荐信至07-10。初步结果约10-16。"
    ),
    english="按SNU指南。",
    requirements="国际研究生材料齐全；注意超短报名窗。",
    funding="有竞争奖学金/导师课题；非人人全奖。",
    fundingLevel="partial",
    applyUrl="https://en.snu.ac.kr/admission",
    portalName="SNU International Graduate Admission",
    notes="错过春入则关注Fall指南。",
    confidence="high",
    source="SNU notice 2027 Spring",
)

add(
    id="postech-phd",
    region="korea",
    regionLabel="韩国",
    degree="phd",
    school="POSTECH",
    campus="浦项",
    qsCs2026="—",
    fields=["CS", "EE", "AI"],
    program="Graduate International",
    intake="Spring 2027",
    deadline="2026-09-11",
    deadlineDetail="2026-07-06～09-11（结果约11-19）面向Spring2027。",
    english="TOEFL等或英语授课证明。",
    requirements="国际生身份规则严格（见指南）。",
    funding="有 — 国际生奖学金/RA常见。",
    fundingLevel="full",
    applyUrl="https://adm-g.postech.ac.kr/",
    portalName="POSTECH Graduate Admission",
    notes="",
    confidence="high",
    source="POSTECH intl guide PDF",
)

add(
    id="yonsei-phd",
    region="korea",
    regionLabel="韩国",
    degree="phd",
    school="Yonsei University",
    campus="首尔",
    qsCs2026="=80",
    fields=["CS", "EE"],
    program="Graduate — 外国人典型",
    intake="2027年3月（春季）",
    deadline="2026-10-14",
    deadlineDetail="外国人典型报名2026-10-07～10-14；面试约11-14；结果约12-04。",
    english="按研招简章。",
    requirements="外国人/海外全程学历等资格类别。",
    funding="奖学金竞争；导师课题。",
    fundingLevel="partial",
    applyUrl="https://graduate.yonsei.ac.kr/",
    portalName="Yonsei Graduate",
    notes="QS CS约80。",
    confidence="high",
    source="Yonsei graduate schedule",
)

add(
    id="koreauniv-phd",
    region="korea",
    regionLabel="韩国",
    degree="phd",
    school="Korea University",
    campus="首尔",
    qsCs2026="82",
    fields=["CS", "EE"],
    program="Graduate International",
    intake="Spring/Fall 2027",
    deadline="查官网",
    deadlineDetail="春秋两季；国际生单独简章。",
    english="英语/韩语项目分流",
    requirements="材料+资格审查",
    funding="部分奖学金",
    fundingLevel="partial",
    applyUrl="https://graduate.korea.ac.kr/",
    portalName="KU Graduate",
    notes="",
    confidence="low",
    source="KU",
)

add(
    id="skku-phd",
    region="korea",
    regionLabel="韩国",
    degree="phd",
    school="Sungkyunkwan University (SKKU)",
    campus="水原/首尔",
    qsCs2026="—",
    fields=["CS", "EE", "AI"],
    program="Graduate",
    intake="2027",
    deadline="查国际招生",
    deadlineDetail="与三星合作强。",
    english="英语项目存在",
    requirements="标准材料",
    funding="部分全奖可能",
    fundingLevel="partial",
    applyUrl="https://www.skku.edu/",
    portalName="SKKU",
    notes="",
    confidence="low",
    source="SKKU",
)

add(
    id="kr-master",
    region="korea",
    regionLabel="韩国",
    degree="master",
    school="KAIST / SNU / POSTECH等",
    campus="韩国",
    qsCs2026="—",
    fields=["CS", "EE"],
    program="MS（国际通道常与PhD同系统）",
    intake="2027 Spring/Fall",
    deadline="同各校国际研究生时间表",
    deadlineDetail="KAIST国际通道MS/PhD共用时间线。",
    english="英语项目为主（KAIST/POSTECH）",
    requirements="学士",
    funding="KAIST/POSTECH国际生常有津贴；SNU更竞争。",
    fundingLevel="partial",
    applyUrl="https://admission.kaist.ac.kr/intl-graduate/",
    portalName="各校国际研究生",
    notes="",
    confidence="medium",
    source="KAIST",
)

# ========== USA ==========
us_phd = [
    ("mit", "Massachusetts Institute of Technology", "1", "CS+EECS", "2026-12-01", "https://gradadmissions.mit.edu/", "EECS；录取后通常全奖。"),
    ("stanford", "Stanford University", "2", "CS", "2026-12-08", "https://www.cs.stanford.edu/admissions-graduate-application-deadlines", "PhD与MS同日截止；Autumn only。"),
    ("cmu", "Carnegie Mellon University", "3", "CS/SCS", "2026-12-09", "https://www.cs.cmu.edu/education/graduate-admissions", "Early 11-18；Final 12-09 15:00 EST；门户9-09开。"),
    ("berkeley", "UC Berkeley", "6", "EECS/CS", "2026-12-01", "https://eecs.berkeley.edu/academics/graduate/research-programs/admissions/", "Fall2027；9月重开系统。"),
    ("harvard", "Harvard University", "7", "CS", "2026-12-15", "https://www.seas.harvard.edu/", "SEAS CS；确认精确日。"),
    ("princeton", "Princeton University", "~15", "CS", "2026-12-15", "https://www.cs.princeton.edu/", ""),
    ("caltech", "Caltech", "40", "CMS/EE", "2026-12-15", "https://www.gradoffice.caltech.edu/", "小而精。"),
    ("cornell", "Cornell University", "17", "CS", "2026-12-15", "https://www.cs.cornell.edu/", "CS主截止12/15；IS可能12/1。"),
    ("ucla", "UCLA", "~20", "CS", "2026-12-15", "https://www.cs.ucla.edu/", ""),
    ("ucsd", "UC San Diego", "~25", "CSE", "2026-12-15", "https://cse.ucsd.edu/", "可微渲染等实验室活跃。"),
    ("uiuc", "UIUC", "~20", "CS", "2026-12-01", "https://cs.illinois.edu/", ""),
    ("uw", "University of Washington", "~20", "CSE", "2026-12-15", "https://www.cs.washington.edu/", "图形/视觉强。"),
    ("gt", "Georgia Tech", "~25", "CS", "2026-12-15", "https://www.cc.gatech.edu/", "23:59 ET。"),
    ("umich", "University of Michigan", "~20", "CSE", "2026-12-15", "https://cse.engin.umich.edu/", ""),
    ("utexas", "UT Austin", "~25", "CS", "2026-12-15", "https://www.cs.utexas.edu/", ""),
    ("columbia", "Columbia University", "~25", "CS", "2026-12-15", "https://www.cs.columbia.edu/", ""),
    ("upenn", "University of Pennsylvania", "~25", "CIS", "2026-12-15", "https://www.cis.upenn.edu/", ""),
    ("yale", "Yale University", "~30", "CS", "2026-12-15", "https://cpsc.yale.edu/", ""),
    ("usc", "University of Southern California", "~30", "CS", "2026-12-15", "https://www.cs.usc.edu/", ""),
    ("nyu", "New York University", "~30", "CS", "2026-12-15", "https://cs.nyu.edu/", "Courant。"),
    ("jhu", "Johns Hopkins University", "=67", "CS", "2026-12-15", "https://www.cs.jhu.edu/", ""),
    ("purdue", "Purdue University", "~40", "CS", "2026-12-01", "https://www.cs.purdue.edu/", ""),
    ("umd", "University of Maryland", "~40", "CS", "2026-12-04", "https://www.cs.umd.edu/", ""),
    ("wisc", "UW–Madison", "~30", "CS", "2026-12-15", "https://www.cs.wisc.edu/", ""),
    ("ucsb", "UC Santa Barbara", "~40", "CS", "2026-12-15", "https://www.cs.ucsb.edu/", ""),
    ("uci", "UC Irvine", "~40", "CS", "2026-12-15", "https://www.cs.uci.edu/", ""),
    ("ucdavis", "UC Davis", "~50", "CS", "2026-12-15", "https://cs.ucdavis.edu/", ""),
    ("ucsc", "UC Santa Cruz", "~50", "CSE", "2027-01-05", "https://www.soe.ucsc.edu/", "较晚。"),
    ("northwestern", "Northwestern University", "~40", "CS", "2026-12-15", "https://www.mccormick.northwestern.edu/computer-science/", ""),
    ("duke", "Duke University", "~40", "CS", "2026-12-15", "https://cs.duke.edu/", ""),
    ("brown", "Brown University", "~40", "CS", "2026-12-15", "https://cs.brown.edu/", ""),
    ("rice", "Rice University", "~50", "CS", "2026-12-15", "https://www.cs.rice.edu/", ""),
    ("vanderbilt", "Vanderbilt University", "~50", "CS", "2026-12-15", "https://engineering.vanderbilt.edu/cs/", ""),
    ("osu", "Ohio State University", "~50", "CSE", "2026-12-15", "https://cse.osu.edu/", ""),
    ("psu", "Penn State", "~50", "CSE", "2026-12-15", "https://www.eecs.psu.edu/", ""),
    ("tamu", "Texas A&M", "~50", "CS", "2026-12-15", "https://engineering.tamu.edu/cse/", ""),
    ("virginia", "University of Virginia", "~50", "CS", "2026-12-15", "https://engineering.virginia.edu/cs", ""),
    ("unc", "UNC Chapel Hill", "~50", "CS", "2027-03-09", "https://cs.unc.edu/", "LEAP列出较晚，仍建议早投。"),
    ("bu", "Boston University", "~50", "CS", "2026-12-15", "https://www.bu.edu/cs/", ""),
    ("northeastern", "Northeastern University", "~50", "Khoury CS", "2026-12-15", "https://www.khoury.northeastern.edu/", ""),
    ("asu", "Arizona State University", "~60", "CSE", "2026-12-15", "https://scai.engineering.asu.edu/", ""),
    ("uf", "University of Florida", "~60", "CISE", "2026-12-15", "https://www.cise.ufl.edu/", ""),
    ("minnesota", "University of Minnesota", "~50", "CS", "2026-12-15", "https://cse.umn.edu/cs", ""),
    ("colorado", "CU Boulder", "~50", "CS", "2026-12-15", "https://www.colorado.edu/cs/", ""),
    ("rutgers", "Rutgers", "~60", "CS", "2026-12-15", "https://www.cs.rutgers.edu/", ""),
    ("stonybrook", "Stony Brook University", "~60", "CS", "2026-12-15", "https://www.cs.stonybrook.edu/", ""),
    ("rpi", "RPI", "~60", "CS", "2026-12-15", "https://www.cs.rpi.edu/", ""),
    ("ncsu", "NC State", "~60", "CS", "2026-12-15", "https://www.csc.ncsu.edu/", ""),
    ("gatech-ece", "Georgia Tech ECE", "~", "EE", "2026-12-15", "https://ece.gatech.edu/", "EE通道与CS分开。"),
    ("illinois-ece", "UIUC ECE", "~", "EE", "2026-12-15", "https://ece.illinois.edu/", "EE单独申请。"),
    ("umich-ee", "University of Michigan ECE", "~", "EE", "2026-12-15", "https://ece.engin.umich.edu/", ""),
    ("ut-ece", "UT Austin ECE", "~", "EE", "2026-12-15", "https://www.ece.utexas.edu/", ""),
    ("uw-ee", "University of Washington ECE", "~", "EE", "2026-12-15", "https://www.ece.uw.edu/", ""),
    ("columbia-ee", "Columbia EE", "~", "EE", "2026-12-15", "https://www.ee.columbia.edu/", ""),
    ("princeton-ee", "Princeton ECE", "~", "EE", "2026-12-15", "https://ece.princeton.edu/", ""),
    ("caltech-ee", "Caltech EE", "40", "EE", "2026-12-15", "https://ee.caltech.edu/", ""),
    ("harvard-se", "Harvard SEAS", "7", "EE/Applied Comp", "2026-12-15", "https://www.seas.harvard.edu/", ""),
    ("epfl-note", "（对照）若同时看欧洲可另开表", "—", "—", "—", "https://www.findaphd.com/", "本表仅五地。"),
]

for sid, school, qs, fields, dl, url, note in us_phd:
    if sid == "epfl-note":
        continue
    fl = fields.split("/") if "/" in fields else fields.split("+")
    conf = "high" if dl.startswith("2026-12") and dl.count("-") == 2 else "medium"
    add(
        id=f"us-{sid}-phd",
        region="usa",
        regionLabel="美国",
        degree="phd",
        school=school,
        campus="美国",
        qsCs2026=str(qs),
        fields=fl,
        program=f"PhD — {fields}",
        intake="Fall 2027",
        deadline=dl,
        deadlineDetail=(
            "美国研究型博士通常「录取即带RA/TA全奖」。"
            "GRE多数CS已可选/取消，以院系页为准。"
            + ((" " + note) if note.strip() else "")
        ),
        english="TOEFL/IELTS（国际生）；部分学校有家考限制。",
        requirements="SoP、CV、成绩单、3封推荐信、语言成绩；列出意向导师。",
        funding="通常全奖（RA/TA/Fellowship）若录取。",
        fundingLevel="full",
        applyUrl=url,
        portalName="大学 Graduate Application Portal",
        notes=note,
        confidence=conf,
        source="LEAP Fall2027 / 官方招生页",
    )

add(
    id="us-msc-general",
    region="usa",
    regionLabel="美国",
    degree="master",
    school="多数 Top CS 院校（如Stanford MS）",
    campus="美国",
    qsCs2026="—",
    fields=["CS", "EE"],
    program="授课型MS（专业硕士）",
    intake="Fall 2027",
    deadline="常与PhD同期或稍晚（12月–2月）",
    deadlineDetail="例：Stanford MS与PhD同为2026-12-08。多数MS自费。",
    english="TOEFL/IELTS",
    requirements="SoP/CV/推荐信；一般弱于PhD的研究要求。",
    funding="多数无全奖；少数TA。想要资助优先申PhD。",
    fundingLevel="rare",
    applyUrl="https://www.cs.stanford.edu/admissions-graduate-application-deadlines",
    portalName="各校 Graduate Portal",
    notes="美国MS与PhD资金模式明确不同。",
    confidence="high",
    source="Stanford CS deadlines",
)

meta = {
    "title": "2027 CS/EE 相关研究生申请导航",
    "generated": "2026-09-13",
    "scope": "香港(+大陆分校)/美国/新加坡/日本/韩国 · PhD优先 · 美国约Top50+EE扩展",
    "disclaimer": "截止日期与语言/资助以官方页面最终为准；本页为联网检索汇总，便于本地筛选与分享。",
    "count": len(records),
    "qsNote": "QS Computer Science & Information Systems 2026 作为参考排序线索",
}

(out / "data.js").write_text(
    "window.ADMISSIONS_DATA = "
    + json.dumps(records, ensure_ascii=False, indent=2)
    + ";\nwindow.ADMISSIONS_META = "
    + json.dumps(meta, ensure_ascii=False, indent=2)
    + ";\n",
    encoding="utf-8",
)

print("OK", len(records))
from collections import Counter

print(Counter(r["region"] for r in records))
print(Counter(r["degree"] for r in records))
